# permissions for end users to view colors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: color-viewer-role
rules:
- apiGroups:
  - stable.example.com
  resources:
  - colors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stable.example.com
  resources:
  - colors/status
  verbs:
  - get
